name: myenv
channels:
  - msys2
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi=20.1.0
  - arviz=0.6.1
  - astroid=2.4.2
  - async_generator=1.10
  - attrs=20.3.0
  - backcall=0.2.0
  - blas=1.0
  - bleach=3.2.1
  - bzip2=1.0.8
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - cffi=1.14.4
  - cftime=1.3.1
  - colorama=0.4.4
  - convertdate=2.2.2
  - curl=7.71.1
  - cycler=0.10.0
  - cython=0.29.21
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - ephem=3.7.7.1
  - et_xmlfile=1.0.1
  - freetype=2.10.4
  - hdf4=4.2.13
  - hdf5=1.10.4
  - holidays=0.10.3
  - icc_rt=2019.0.0
  - icu=58.2
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.19.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - isort=5.6.4
  - jdcal=1.4.1
  - jedi=0.18.0
  - jinja2=2.11.2
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.7.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.0
  - korean_lunar_calendar=0.2.1
  - krb5=1.18.2
  - lazy-object-proxy=1.4.3
  - libcurl=7.71.1
  - libnetcdf=4.7.3
  - libpng=1.6.37
  - libpython=2.1
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libtiff=4.1.0
  - lunarcalendar=0.0.9
  - lz4-c=1.9.2
  - m2w64-binutils=2.25.1
  - m2w64-bzip2=1.0.6
  - m2w64-crt-git=5.0.0.4636.2595836
  - m2w64-gcc=5.3.0
  - m2w64-gcc-ada=5.3.0
  - m2w64-gcc-fortran=5.3.0
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gcc-objc=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-headers-git=5.0.0.4636.c0ad18a
  - m2w64-isl=0.16.1
  - m2w64-libiconv=1.14
  - m2w64-libmangle-git=5.0.0.4509.2e5a9a2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-make=4.1.2351.a80a8b8
  - m2w64-mpc=1.0.3
  - m2w64-mpfr=3.1.4
  - m2w64-pkg-config=0.29.1
  - m2w64-toolchain=5.3.0
  - m2w64-toolchain_win-64=2.4.0
  - m2w64-tools-git=5.0.0.4592.90b8472
  - m2w64-windows-default-manifest=6.4
  - m2w64-winpthreads-git=5.0.0.4634.697f757
  - m2w64-zlib=1.2.8
  - markupsafe=1.1.1
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - msys2-conda-epoch=20160418
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - nest-asyncio=1.4.3
  - netcdf4=1.5.3
  - notebook=6.1.6
  - numpy=1.19.1
  - numpy-base=1.19.1
  - olefile=0.46
  - openpyxl=3.0.5
  - openssl=1.1.1i
  - packaging=20.8
  - pandas=1.1.5
  - pandoc=2.11
  - pandocfilters=1.4.3
  - parso=0.7.0
  - patsy=0.5.1
  - pickleshare=0.7.5
  - pillow=8.1.0
  - pip=20.3.3
  - plotly=4.14.3
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.8
  - prompt_toolkit=3.0.8
  - pycparser=2.20
  - pygments=2.7.4
  - pylint=2.6.0
  - pymeeus=0.3.7
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pystan=2.19.1.1
  - python=3.7.9
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2020.5
  - pywin32=227
  - pywinpty=0.5.7
  - pyzmq=20.0.0
  - qt=5.9.7
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - retrying=1.3.3
  - scipy=1.5.2
  - seaborn=0.11.0
  - send2trash=1.5.0
  - setuptools=51.3.3
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.33.0
  - statsmodels=0.12.0
  - terminado=0.9.2
  - testpath=0.4.4
  - tk=8.6.10
  - toml=0.10.1
  - tornado=6.1
  - tqdm=4.55.1
  - traitlets=5.0.5
  - typed-ast=1.4.2
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - wincertstore=0.2
  - winpty=0.4.3
  - wrapt=1.11.2
  - xarray=0.16.2
  - xz=5.2.5
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - altair==4.1.0
    - astor==0.8.1
    - base58==2.0.1
    - blinker==1.4
    - cachetools==4.1.1
    - chardet==3.0.4
    - click==7.1.2
    - cmdstanpy==0.9.5
    - fbprophet==0.7.1
    - gitdb==4.0.5
    - gitpython==3.1.11
    - idna==2.10
    - pathtools==0.1.2
    - protobuf==3.14.0
    - pyarrow==2.0.0
    - pydeck==0.5.0
    - requests==2.25.0
    - setuptools-git==1.2
    - smmap==3.0.4
    - streamlit==0.81
    - toolz==0.11.1
    - tzlocal==2.1
    - urllib3==1.26.2
    - validators==0.18.1
    - watchdog==0.10.4
    - xlrd==1.2.0
prefix: C:\Users\michael.lin\Miniconda3\envs\myenv
