name: myenv
channels:
  - plotly
  - msys2
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi=20.1.0=py37he774522_1
  - arviz=0.10.0=py_0
  - astroid=2.4.2=py37_0
  - async_generator=1.10=py37h28b3542_0
  - attrs=20.2.0=py_0
  - backcall=0.2.0=py_0
  - blas=1.0=mkl
  - bleach=3.2.1=py_0
  - bzip2=1.0.8=he774522_3
  - ca-certificates=2020.6.20=hecda079_0
  - certifi=2020.6.20=py37hf50a25e_2
  - cffi=1.14.3=py37h7a1dbc1_0
  - cftime=1.2.1=py37h3a3b6f7_1
  - colorama=0.4.3=py_0
  - convertdate=2.2.2=pyh9f0ad1d_0
  - curl=7.71.1=h4b64cdc_8
  - cycler=0.10.0=py37_0
  - cython=0.29.21=py37h8e8dfb5_1
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_0
  - ephem=3.7.7.1=py37h4ab8f01_1
  - et_xmlfile=1.0.1=py_1001
  - freetype=2.10.2=hd328e21_0
  - hdf4=4.2.13=h712560f_2
  - hdf5=1.10.4=nompi_hcc15c50_1106
  - holidays=0.10.3=pyh9f0ad1d_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - importlib-metadata=1.7.0=py37_0
  - importlib_metadata=1.7.0=0
  - intel-openmp=2020.2=254
  - ipykernel=5.3.4=py37h5ca1d4c_0
  - ipython=7.18.1=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - ipywidgets=7.5.1=py_1
  - isort=5.5.4=py37_0
  - jdcal=1.4.1=py_0
  - jedi=0.17.2=py37_0
  - jinja2=2.11.2=py_0
  - jpeg=9b=hb83a4c4_2
  - jsonschema=3.2.0=py37_1
  - jupyter=1.0.0=py37_7
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_core=4.6.3=py37_0
  - jupyterlab_pygments=0.1.2=py_0
  - kiwisolver=1.2.0=py37h74a9793_0
  - korean_lunar_calendar=0.2.1=pyh9f0ad1d_0
  - krb5=1.17.1=hc04afaa_3
  - lazy-object-proxy=1.4.3=py37he774522_0
  - libcurl=7.71.1=h4b64cdc_8
  - libnetcdf=4.7.3=h1302dcc_0
  - libpng=1.6.37=h2a8f88b_0
  - libpython=2.1=py37_0
  - libsodium=1.0.18=h62dcd97_0
  - libssh2=1.9.0=hb06d900_5
  - libtiff=4.1.0=h56a325e_1
  - lunarcalendar=0.0.9=py_0
  - lz4-c=1.9.2=h62dcd97_1
  - m2w64-binutils=2.25.1=5
  - m2w64-bzip2=1.0.6=6
  - m2w64-crt-git=5.0.0.4636.2595836=2
  - m2w64-gcc=5.3.0=6
  - m2w64-gcc-ada=5.3.0=6
  - m2w64-gcc-fortran=5.3.0=6
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gcc-objc=5.3.0=6
  - m2w64-gmp=6.1.0=2
  - m2w64-headers-git=5.0.0.4636.c0ad18a=2
  - m2w64-isl=0.16.1=2
  - m2w64-libiconv=1.14=6
  - m2w64-libmangle-git=5.0.0.4509.2e5a9a2=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - m2w64-make=4.1.2351.a80a8b8=2
  - m2w64-mpc=1.0.3=3
  - m2w64-mpfr=3.1.4=4
  - m2w64-pkg-config=0.29.1=2
  - m2w64-toolchain=5.3.0=7
  - m2w64-toolchain_win-64=2.4.0=0
  - m2w64-tools-git=5.0.0.4592.90b8472=2
  - m2w64-windows-default-manifest=6.4=3
  - m2w64-winpthreads-git=5.0.0.4634.697f757=2
  - m2w64-zlib=1.2.8=10
  - markupsafe=1.1.1=py37hfa6e2cd_1
  - matplotlib=3.3.1=0
  - matplotlib-base=3.3.1=py37hba9282a_0
  - mccabe=0.6.1=py37_1
  - mistune=0.8.4=py37hfa6e2cd_1001
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37hb782905_0
  - mkl_fft=1.2.0=py37h45dec08_0
  - mkl_random=1.1.1=py37h47e9c7a_0
  - msys2-conda-epoch=20160418=1
  - nbclient=0.5.0=py_0
  - nbconvert=6.0.7=py37_0
  - nbformat=5.0.7=py_0
  - nest-asyncio=1.4.1=py_0
  - netcdf4=1.5.3=py37h012c1a0_0
  - notebook=6.1.4=py37_0
  - numpy=1.19.1=py37h5510c5b_0
  - numpy-base=1.19.1=py37ha3acd2a_0
  - olefile=0.46=py_0
  - openpyxl=3.0.5=py_0
  - openssl=1.1.1h=he774522_0
  - packaging=20.4=py_0
  - pandas=1.1.2=py37ha925a31_0
  - pandoc=2.10.1=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.7.0=py_0
  - patsy=0.5.1=py37_0
  - pickleshare=0.7.5=py37_1001
  - pillow=7.2.0=py37hcc1f983_0
  - pip=20.2.3=py37_0
  - plotly=4.12.0=py_0
  - prometheus_client=0.8.0=py_0
  - prompt-toolkit=3.0.7=py_0
  - prompt_toolkit=3.0.7=0
  - pycparser=2.20=py_2
  - pygments=2.7.1=py_0
  - pylint=2.6.0=py37_0
  - pymeeus=0.3.7=pyh9f0ad1d_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py37h6538335_2
  - pyrsistent=0.17.3=py37he774522_0
  - pystan=2.19.1.1=py37h9758500_2
  - python=3.7.9=h60c2a47_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2020.1=py_0
  - pywin32=227=py37he774522_1
  - pywinpty=0.5.7=py37_0
  - pyzmq=19.0.2=py37ha925a31_1
  - qt=5.9.7=vc14h73c81de_0
  - qtconsole=4.7.7=py_0
  - qtpy=1.9.0=py_0
  - retrying=1.3.3=py37_2
  - scipy=1.5.2=py37h9439919_0
  - seaborn=0.11.0=py_0
  - send2trash=1.5.0=py37_0
  - setuptools=50.3.0=py37h9490d1a_1
  - sip=4.19.8=py37h6538335_0
  - six=1.15.0=py_0
  - sqlite=3.33.0=h2a8f88b_0
  - statsmodels=0.12.0=py37he774522_0
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=he774522_0
  - toml=0.10.1=py_0
  - tornado=6.0.4=py37he774522_1
  - tqdm=4.51.0=pyh9f0ad1d_0
  - traitlets=5.0.4=py_0
  - typed-ast=1.4.1=py37he774522_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_3
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py37_1
  - wheel=0.35.1=py_0
  - widgetsnbextension=3.5.1=py37_0
  - wincertstore=0.2=py37_0
  - winpty=0.4.3=4
  - wrapt=1.11.2=py37he774522_0
  - xarray=0.16.1=py_0
  - xz=5.2.5=h62dcd97_0
  - zeromq=4.3.2=ha925a31_3
  - zipp=3.3.0=py_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.4.5=h04227a9_0
  - pip:
    - altair==4.1.0
    - astor==0.8.1
    - base58==2.0.1
    - blinker==1.4
    - cachetools==4.1.1
    - chardet==3.0.4
    - click==7.1.2
    - cmdstanpy==0.9.5
    - fbprophet==0.7.1
    - gitdb==4.0.5
    - gitpython==3.1.11
    - idna==2.10
    - pathtools==0.1.2
    - protobuf==3.14.0
    - pyarrow==2.0.0
    - pydeck==0.5.0
    - requests==2.25.0
    - setuptools-git==1.2
    - smmap==3.0.4
    - streamlit==0.72.0
    - toolz==0.11.1
    - tzlocal==2.1
    - urllib3==1.26.2
    - validators==0.18.1
    - watchdog==0.10.4
    - xlrd==1.2.0
prefix: C:\Users\michael.lin\Miniconda3\envs\myenv

