name: dashboard
channels:
  - conda-forge
  - defaults
dependencies:
  - astroid=2.4.2=py38_0
  - blas=1.0=mkl
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=py38_0
  - colorama=0.4.4=py_0
  - cycler=0.10.0=py38_0
  - freetype=2.10.4=hd328e21_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - intel-openmp=2020.2=254
  - isort=5.6.4=py_0
  - jpeg=9b=hb83a4c4_2
  - kiwisolver=1.2.0=py38h74a9793_0
  - lazy-object-proxy=1.4.3=py38he774522_0
  - libpng=1.6.37=h2a8f88b_0
  - libtiff=4.1.0=h56a325e_1
  - lz4-c=1.9.2=hf4a77e7_3
  - matplotlib=3.3.1=0
  - matplotlib-base=3.3.1=py38hba9282a_0
  - mccabe=0.6.1=py38_1
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38hb782905_0
  - mkl_fft=1.2.0=py38h45dec08_0
  - mkl_random=1.1.1=py38h47e9c7a_0
  - numpy=1.19.1=py38h5510c5b_0
  - numpy-base=1.19.1=py38ha3acd2a_0
  - olefile=0.46=py_0
  - openssl=1.1.1h=he774522_0
  - pandas=1.1.3=py38ha925a31_0
  - patsy=0.5.1=py38_0
  - pillow=8.0.1=py38h4fa10fc_0
  - pip=20.2.4=py38_0
  - pylint=2.6.0=py38_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py38ha925a31_4
  - python=3.8.5=h5fd99cc_1
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2020.1=py_0
  - qt=5.9.7=vc14h73c81de_0
  - scipy=1.5.0=py38h9439919_0
  - seaborn=0.11.0=py_0
  - setuptools=50.3.0=py38h9490d1a_1
  - sip=4.19.13=py38ha925a31_0
  - six=1.15.0=py_0
  - sqlite=3.33.0=h2a8f88b_0
  - statsmodels=0.12.0=py38h1e00858_1
  - tk=8.6.10=he774522_0
  - toml=0.10.1=py_0
  - tornado=6.0.4=py38he774522_1
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_3
  - wheel=0.35.1=py_0
  - wincertstore=0.2=py38_0
  - wrapt=1.11.2=py38he774522_0
  - xlrd=1.2.0=py_0
  - xz=5.2.5=h62dcd97_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.4.5=h04227a9_0
  - pip:
    - altair==4.1.0
    - argon2-cffi==20.1.0
    - astor==0.8.1
    - async-generator==1.10
    - attrs==20.2.0
    - backcall==0.2.0
    - base58==2.0.1
    - bleach==3.2.1
    - blinker==1.4
    - boto3==1.15.14
    - botocore==1.18.14
    - cachetools==4.1.1
    - cffi==1.14.3
    - chardet==3.0.4
    - click==7.1.2
    - decorator==4.4.2
    - defusedxml==0.6.0
    - entrypoints==0.3
    - enum-compat==0.0.3
    - idna==2.10
    - ipykernel==5.3.4
    - ipython==7.18.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.17.2
    - jinja2==2.11.2
    - jmespath==0.10.0
    - jsonschema==3.2.0
    - jupyter-client==6.1.7
    - jupyter-core==4.6.3
    - jupyterlab-pygments==0.1.2
    - markupsafe==1.1.1
    - mistune==0.8.4
    - nbclient==0.5.0
    - nbconvert==6.0.7
    - nbformat==5.0.7
    - nest-asyncio==1.4.1
    - notebook==6.1.4
    - packaging==20.4
    - pandocfilters==1.4.2
    - parso==0.7.1
    - pathtools==0.1.2
    - pickleshare==0.7.5
    - prometheus-client==0.8.0
    - prompt-toolkit==3.0.7
    - protobuf==3.13.0
    - pyarrow==1.0.1
    - pycparser==2.20
    - pydeck==0.5.0b1
    - pygments==2.7.1
    - pyrsistent==0.17.3
    - pywin32==228
    - pywinpty==0.5.7
    - pyzmq==19.0.2
    - requests==2.24.0
    - s3transfer==0.3.3
    - send2trash==1.5.0
    - streamlit==0.67.1
    - terminado==0.9.1
    - testpath==0.4.4
    - toolz==0.11.1
    - traitlets==5.0.4
    - tzlocal==2.1
    - urllib3==1.25.10
    - validators==0.18.1
    - watchdog==0.10.3
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
prefix: C:\Users\michael.lin\Miniconda3\envs\dashboard

